x_list = [1,2,3,4,5,6,7]
print(x_list)
x_list = iter(x_list)
print(type(x_list))
print(next(x_list))
print(next(x_list))
print(next(x_list))
print(next(x_list))
print(next(x_list))
print(next(x_list))
print(next(x_list))